"""
Code_2: Modular Voxel Grid Assembly and Domain Construction

This script loads the 147 voxelized ballast sub-blocks generated by Code_1
and assembles them into a structured 7 × 7 × 3 layout to construct the
final high-resolution heterogeneous ballast domain (0.7 m × 0.7 m × 0.3 m).

The workflow includes:
- Loading individual HDF5 voxel blocks
- Systematic 3D grid assembly
- Boundary correction across internal block interfaces
- 2D projection visualization (x–y plane, z as depth)
- Export of the combined HDF5 volume
- Generation of a filled/void volumetric report

Author: Sepideh Harajchi
Affiliation: Delft University of Technology, Department of Geoscience and Engineering

Associated manuscript:
"Numerical Investigation of GPR Performance Over Voxelized Heterogeneous Railway Ballast:
Influence of Layer Composition and Antenna Frequency"
"""

import os
import h5py
import numpy as np
import matplotlib.pyplot as plt

# Base repository directory
base_address = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Output directory shared with Code_1
output_dir = os.path.join(base_address, "Output")

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# File paths for the 147 HDF5 files produced by Code_1
file_paths = [
    os.path.join(output_dir, f"systematic_voxel_data_with_colors_{i}.h5")
    for i in range(1, 148)
]


def load_hdf5_data(file_paths):
    """Load voxel data and voxel size from HDF5 files."""
    voxel_data_list = []
    voxel_size = None

    for path in file_paths:
        if not os.path.exists(path):
            print(f"Error: File not found - {path}")
            continue

        with h5py.File(path, 'r') as f:
            data = f['data'][:]
            voxel_data_list.append(data)

            if voxel_size is None:
                voxel_size = f.attrs['dx_dy_dz']

    return voxel_data_list, voxel_size


def combine_voxel_grids(voxel_data_list):
    """Combine 147 voxel blocks into a 7 × 7 × 3 grid."""
    individual_shape = voxel_data_list[0].shape
    combined_shape = (
        individual_shape[0] * 7,
        individual_shape[1] * 7,
        individual_shape[2] * 3
    )
    combined_grid = np.zeros(combined_shape, dtype=np.int8)

    for idx, voxel_data in enumerate(voxel_data_list):
        row = (idx // 7) % 7
        col = idx % 7
        layer = idx // 49

        combined_grid[
            row * individual_shape[0]:(row + 1) * individual_shape[0],
            col * individual_shape[1]:(col + 1) * individual_shape[1],
            layer * individual_shape[2]:(layer + 1) * individual_shape[2]
        ] = voxel_data

    return combined_grid


def set_corrected_boundary_values_optimized(grid, voxel_data_list):
    """Apply boundary correction across internal block interfaces."""
    block_shape = voxel_data_list[0].shape
    n_layers = grid.shape[2] // block_shape[2]

    for row in range(7):
        for layer in range(n_layers):
            x_min_block = voxel_data_list[(row + 1) * 7 - 1 + layer * 49]
            x_max_block = voxel_data_list[row * 7 + layer * 49]

            grid[
                row * block_shape[0],
                :,
                layer * block_shape[2]:(layer + 1) * block_shape[2]
            ] = np.tile(x_min_block[-1, :, :], (7, 1))

            grid[
                (row + 1) * block_shape[0] - 1,
                :,
                layer * block_shape[2]:(layer + 1) * block_shape[2]
            ] = np.tile(x_max_block[0, :, :], (7, 1))

    for col in range(7):
        for layer in range(n_layers):
            y_min_block = voxel_data_list[(col + 1) * 7 - 1 + layer * 49]
            y_max_block = voxel_data_list[col * 7 + layer * 49]

            grid[
                :,
                col * block_shape[1],
                layer * block_shape[2]:(layer + 1) * block_shape[2]
            ] = np.repeat(y_min_block[:, -1, :], 7, axis=0)

            grid[
                :,
                (col + 1) * block_shape[1] - 1,
                layer * block_shape[2]:(layer + 1) * block_shape[2]
            ] = np.repeat(y_max_block[:, 0, :], 7, axis=0)

    z_min_block = voxel_data_list[-1]
    z_max_block = voxel_data_list[-1]
    grid[:, :, 0] = np.tile(z_min_block[:, :, -1], (7, 7))
    grid[:, :, -1] = np.tile(z_max_block[:, :, 0], (7, 7))

    return grid


def visualize_2d_projection(grid, voxel_size, output_path):
    """Create a 2D projection in the x–y plane with z as depth."""
    projection = np.sum(grid, axis=2)
    x_extent = grid.shape[0] * voxel_size[0]
    y_extent = grid.shape[1] * voxel_size[1]

    plt.figure()
    plt.imshow(
        projection.T,
        cmap='viridis',
        extent=[0, x_extent, 0, y_extent],
        origin='lower'
    )
    plt.colorbar(label='Occupied Voxel Count')
    plt.title('2D Projection of Combined Voxel Grid (x-y plane with z as depth)')
    plt.xlabel('X-axis (meters)')
    plt.ylabel('Y-axis (meters)')
    plt.savefig(output_path)
    plt.close()


def save_to_hdf5(grid, voxel_size, output_path):
    """Save combined voxel data to HDF5."""
    with h5py.File(output_path, 'w') as f:
        f.attrs['dx_dy_dz'] = voxel_size
        f.attrs['box_size'] = np.array([0.7, 0.7, 0.3])
        f.create_dataset("data", data=grid, dtype=np.int8)


def generate_corrected_report(grid, output_path):
    """Generate a report with filled and void voxel percentages."""
    total_voxels = grid.size
    stone_voxels = np.sum(grid == 0)
    void_voxels = np.sum(grid == -1)

    filled_percentage = (stone_voxels / total_voxels) * 100
    void_percentage = (void_voxels / total_voxels) * 100

    report_text = f"""Voxel Grid Report
-----------------
Total Voxels: {total_voxels}
Stone (Filled) Percentage: {filled_percentage:.2f}%
Void (Empty) Percentage: {void_percentage:.2f}%
"""

    with open(output_path, 'w') as file:
        file.write(report_text)

    print(report_text)


def main_with_colored_visualization():
    """Main workflow for loading, combining, correcting, and exporting the voxel domain."""
    voxel_data_list, voxel_size = load_hdf5_data(file_paths)

    if len(voxel_data_list) < 147:
        print("Error: Not all HDF5 files were loaded successfully.")
        return

    combined_grid = combine_voxel_grids(voxel_data_list)
    combined_grid = set_corrected_boundary_values_optimized(combined_grid, voxel_data_list)

    output_2d_path = os.path.join(output_dir, "combined_voxel_2d_colored_boundary_xy_z_depth.png")
    output_hdf5_path = os.path.join(output_dir, "combined_voxel_data_with_colored_boundary_xy_z_depth.h5")
    output_report_path = os.path.join(output_dir, "voxel_grid_report_corrected_xy_z_depth.txt")

    visualize_2d_projection(combined_grid, voxel_size, output_2d_path)
    save_to_hdf5(combined_grid, voxel_size, output_hdf5_path)
    generate_corrected_report(combined_grid, output_report_path)

    print(f"2D Projection saved at: {output_2d_path}")
    print(f"HDF5 File saved at: {output_hdf5_path}")
    print(f"Report saved at: {output_report_path}")


if __name__ == "__main__":
    main_with_colored_visualization()
